const Constants = {
  DATA: 'DATA',
  DATA_SUCCESS: 'DATA_SUCCESS',
  DATA_FAIL: 'DATA_FAIL',

  ALLOT_ACTIONS: 'ALLOT_ACTIONS',
  ALLOT_ACTIONS_SUCCESS: 'ALLOT_ACTIONS_SUCCESS',
  ALLOT_ACTIONS_FAIL: 'ALLOT_ACTIONS_FAIL',
};

export default Constants;
