// export default {
//     LOGIN_ACTIONS = 'LOGIN_ACTIONS',
//     LOGIN_ACTIONS_SUCCESS = 'LOGIN_ACTIONS_SUCCESS',
//     LOGIN_ACTIONS_FAIL = 'LOGIN_ACTIONS_FAIL'
// };

export const LOGIN_ACTIONS = 'LOGIN_ACTIONS';
export const LOGIN_ACTIONS_SUCCESS = 'LOGIN_ACTIONS_SUCCESS';
export const LOGIN_ACTIONS_FAIL = 'LOGIN_ACTIONS_FAIL';
export const DATA = 'DATA';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAIL = 'DATA_FAIL';
